### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by andretf** [Sertion/vscode-gitblame#155]
VSCode Insiders 1.83.0
MacOs Ventura 13.5.2

Error logged to Dev tools Console:

```
console.ts:137 [Extension Host] Unhandled promise rejection:  TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at D.normalizeWindowsDriveLetter (/Users/andre/.vscode-insiders/extensions/waderyan.gitblame-10.5.0/out/src/index.js:2:7615)
    at D.addFile (/Users/andre/.vscode-insiders/extensions/waderyan.gitblame-10.5.0/out/src/index.js:2:7289)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) (at console.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:125:112226))
$ @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:456
Q @ rpcProtocol.ts:441
M @ rpcProtocol.ts:371
L @ rpcProtocol.ts:297
(anonymous) @ rpcProtocol.ts:161
z @ event.ts:1138
fire @ event.ts:1169
fire @ ipc.net.ts:650
X.onmessage @ localProcessExtensionHost.ts:581

```

**Comment by Sertion** [comment]
Hey Andre. Thanks for the report!

I'll see if I can get a fix out pretty soon.

**Comment by Sertion** [comment]
A new version has been uploaded to the marketplace. Sometimes it can take a few hours for it to appear for everyone.

**Comment by andretf** [comment]
that was fast! thank you so much
