### ISSUE TITLE
Status Bar block disappears after a change in extension settings

### ISSUE THREAD

**Issue by ADTC** [Sertion/vscode-gitblame#170]
Steps to reproduce:

1. Ensure you're seeing the blame in status bar when inside a committed file.
2. Open "Settings" and search for `gitblame`.
3. Toggle "Inline Message Enabled". (You can try with other settings too. The checkbox is just an easy way to reproduce.)
4. Go back to the file, and observe that the blame is no longer shown in status bar.
   * If the option in step 3 was turned on, you should still see the blame on the editor line.

Also, I observe crashes in the Extension Host output:

```
2024-04-30 08:20:25.093 [info] Extension host terminating: renderer closed the MessagePort
// --- Following stack trace repeats twice. ---
2024-04-30 08:20:25.116 [error] Canceled: Canceled
	at new O (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:142:46998)
	at u.U (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:149:5539)
	at F.<computed>.T.charCodeAt.F.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:149:2993)
	at d.g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:186335)
	at d.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:185773)
	at E.registerCommand.description (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:185097)
	at d.h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:186874)
	at d.g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:185866)
	at d.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:185773)
	at Object.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:162:22785)
	at set hasGitHubRepositories [as hasGitHubRepositories] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github/dist/extension.js:2:324866)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github/dist/extension.js:2:325825
	at o.value (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:1051703)
	at s.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:659)
	at s.z (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:729)
	at s.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:945)
	at Object.m [as dispose] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:964886)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:970920
	at Array.forEach (<anonymous>)
	at f.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:970906)
	at a.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:3830)
	at a.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:3927)
	at a.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:948059)
	at a.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:3927)
	at o (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:714)
	at m.eb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:9967)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:7816
	at Array.map (<anonymous>)
	at m.$ (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:7803)
	at m.terminate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:8077)
	at o.terminate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:162:1513)
	at t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:9917)
	at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:6342)
	at MessagePortMain.emit (node:events:517:28)
	at MessagePortMain.emit (node:domain:489:12)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285) setContext undefined
2024-04-30 08:20:25.118 [info] Extension host with pid 59889 exiting with code 0
2024-04-30 08:20:25.887 [info] Extension host with pid 60123 started
```

Current workaround: Run the command "Developer: Reload window" after any change in the extension settings.

Possibly related: #151 #59

**Comment by Sertion** [comment]
Hey ADTC! Thanks for the bug report.

That looks very weird. Will try digging into it, but I have no intimidate idea based on the stack trace.

**Comment by Sertion** [comment]
The stack trace does not seam to be related to the `waderyan.gitblame` extension but the `vscode.git` extension.

I did find an issue related to changing settings and the status bar disappearing and have been able to fix it. The change should be in the next version.
